id: P001765
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:20:08.652708
source_metadata:
  id: bdr:W2CZ6243
  title: ངག་དབང་དཔལ་བཟང་གི་རྣམ་ཐར་
  author: ''
  volumes:
    170c9efe263946e88fd3acb1b8292db4:
      image_group_id: I1KG1581
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
